### ISSUE TITLE
dbt fails with go1.16

### ISSUE THREAD

**Issue by paulhankin** [daedaleanai/dbt#24] opened 2021-02-23 15:55 UTC
dbt doesn't seem to work with go1.16 because what looks like module issues. Perhaps GO111MODULE=off needs explicitly setting when calling go from dbt?

```
$ go version
go version go1.16 linux/amd64

$ dbt build SomeTarget
go: dbt@v0.0.0 (replaced by github.com/daedaleanai/dbt@v0.1.8): missing go.sum entry; to add it:
	go mod download dbt
Error: Failed to run generator in mode 'targets': exit status 1.
A fatal error occured. Exiting...

```

**Comment by jfrohnhofen** [comment] 2021-02-23 17:56
The issue is caused by go 1.16 no longer modifying go.sum by default. We now run 'go mod download' before building the generator. Fixed in version v0.1.11

**Closed by jfrohnhofen** 2021-02-23 17:56 UTC
