### ISSUE TITLE
feaure request: dbt run

### ISSUE THREAD

**Issue by paulhankin** [daedaleanai/dbt#86] opened 2021-09-08 10:00 UTC
I'm currently using something like this to run a test:

    export X=x/y/test/YTest ; dbt build $X cc-toolchain=mytoolchain && dbt build $X cc-toolchain=mytoolchain | tail -n1 | source /dev/stdin

This isn't ideal for many many reasons :D

To improve usability, and to avoid the nastiness of parsing and executing the stdout of dbt, how about:

    dbt run x/y/test/YTest cc-toolchain=mytoolchain

**Comment by jfrohnhofen** [comment] 2021-09-09 08:04
I think the best way to implement this would be with a `runnable` interface (similar to the existing `buildable` interface). I.e., you can implement a custom `Run` method for your build rule struct that returns the command to be run. I'll hopefully get round to implementing this tomorrow.

**Comment by jfrohnhofen** [comment] 2021-09-13 07:20
duplicate of #18

**Closed by jfrohnhofen** 2021-09-13 07:20 UTC
